#!/usr/bin/env bash
# Install and configure Nginx on the server

apt-get update
apt-get install nginx -y
ufw allow 'Nginx HTTP'
rm /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.html
service nginx start
